import Head from 'next/head';
import ListContact from '../../src/Contact/Show_List_Contact/list_contact';
import Header from '../../src/Home/header';
import Bottom from '../../src/Home/footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Danh Sách Phản Hồi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <ListContact></ListContact>
      <Bottom></Bottom>
    </div>
  )
}
