import styles from '../styles/Home.module.css';
import Head from 'next/head';
import  Header  from '../src/Home/header';
import  Footer  from '../src/Home/footer';
import Contact from '../src/Contact/Contact_form';

export default function Home() {
  return (
    <div>
            <Head>
              <title>Liên Hệ</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
        <Header></Header>
        <Contact></Contact>
        <Footer></Footer>
    </div>
  )
}
