import Head from 'next/head';
import  Header  from '../src/Home/header';
import  Main  from '../src/Home/main';
import  Footer  from '../src/Home/footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.test_hiden}>
        <Header></Header>
        <Main></Main>
        <Footer></Footer>
      </div>
    </div>
  )
}
