import styles from '../styles/Home.module.css';
import Head from 'next/head';
import  Header  from '../src/Home/header';
import  Footer  from '../src/Home/footer';
import Login from '../src/Auth/Login';

export default function Home() {
  return (
    <div className={styles.container}>
            <Head>
              <title>Login</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
        <Header></Header>
        <Login></Login>
        <Footer></Footer>
    </div>
  )
}
