import styles from '../styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  return (
    <div className={styles.container}>
            <Head>
              <title>Login</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
        <h1 className={styles.title}>
          Login
        </h1>
    </div>
  )
}
